version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: outer-sports-baller-v3
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
    env_file:
      - .env
    restart: unless-stopped
