import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import ClientLayout from "@/components//layout/ClientLayout";

const apexMk2 = localFont({
  src: [{ path: "../../public/fonts/ApexMk2-Regular.woff", weight: "300", style: "normal" }],
  variable: "--font-apex",
  display: "swap",
});

const geist = Geist({ subsets: ["latin"], variable: "--font-geist" });
const geistMono = Geist_Mono({ subsets: ["latin"], variable: "--font-geist-mono" });

export const metadata: Metadata = {
  title: "Outer Sports Baller V3",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${apexMk2.variable} ${geist.variable} ${geistMono.variable} font-apex relative`}
      >
        <ClientLayout>
          <div className="px-[5.625rem]">
            <div className="overlay" />
            <Navbar />
            {children}
          </div>
          <Footer />
        </ClientLayout>
      </body>
    </html>
  );
}
