import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const apexMk2 = localFont({
  src: [
    {
      path: '../../public/fonts/ApexMk2-Regular.woff',
      weight: '300',
      style: 'normal'
    }
  ],
  variable: '--font-apex',
  display: 'swap',
});

// Google fonts
const geist = Geist({
  subsets: ['latin'],
  variable: '--font-geist',
});

const geistMono = Geist_Mono({
  subsets: ['latin'],
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${apexMk2.variable} ${geist.variable} ${geistMono.variable} font-apex`}>
        {children}
      </body>
    </html>
  );
}